const fs = require('fs');
const path = require('path');

// Load .env file if it exists (local development)
// In Netlify, environment variables are already in process.env
const envPath = path.resolve(__dirname, '../.env');
if (fs.existsSync(envPath)) {
  require('dotenv').config({ path: envPath });
}

// Get environment variables
const apiUrl = process.env.API_URL || 'https://api.delcoronascardigli.com/.netlify/functions/rate-portal';
const apiUrlDev = process.env.API_URL_DEV || 'http://localhost:8888/.netlify/functions/rate-portal';

// Environment file templates
const environmentDev = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually

export const environment = {
  production: false,
  apiUrl: '${apiUrlDev}'
};
`;

const environmentProd = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually

export const environment = {
  production: true,
  apiUrl: '${apiUrl}'
};
`;

// Ensure environments directory exists
const envDir = path.resolve(__dirname, '../src/environments');
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

// Write environment files
fs.writeFileSync(path.join(envDir, 'environment.ts'), environmentDev);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), environmentProd);

console.log('Environment files generated successfully');
console.log(`  - API URL (prod): ${apiUrl}`);
console.log(`  - API URL (dev):  ${apiUrlDev}`);
