const fs = require('fs');
const path = require('path');

console.log('===========================================');
console.log('SET-ENV: Starting environment configuration');
console.log('===========================================');

// Load .env file if it exists (local development)
// In Netlify, environment variables are already in process.env
const envPath = path.resolve(__dirname, '../.env');
console.log('SET-ENV: Looking for .env at:', envPath);

if (fs.existsSync(envPath)) {
  console.log('SET-ENV: .env file FOUND - loading...');
  require('dotenv').config({ path: envPath });
} else {
  console.log('SET-ENV: .env file NOT FOUND - using process.env (Netlify)');
}

// Get environment variables
console.log('SET-ENV: Reading API_URL from process.env:', process.env.API_URL || '(not set)');
console.log('SET-ENV: Reading API_URL_DEV from process.env:', process.env.API_URL_DEV || '(not set)');

const apiUrl = process.env.API_URL || 'https://api-internal-test.netlify.app/api/rate-portal';
const apiUrlDev = process.env.API_URL_DEV || 'http://localhost:8888/api/rate-portal';

// Environment file templates
const environmentDev = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually

export const environment = {
  production: false,
  apiUrl: '${apiUrlDev}'
};
`;

const environmentProd = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually

export const environment = {
  production: true,
  apiUrl: '${apiUrl}'
};
`;

// Ensure environments directory exists
const envDir = path.resolve(__dirname, '../src/environments');
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

// Write environment files
fs.writeFileSync(path.join(envDir, 'environment.ts'), environmentDev);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), environmentProd);

console.log('Environment files generated successfully');
console.log(`  - API URL (prod): ${apiUrl}`);
console.log(`  - API URL (dev):  ${apiUrlDev}`);
